// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9MuqAGoPnpsLiDZ86g9Z4rGhbFcQHAUw',
    appId: '1:570073970473:web:cde0872665b6e539a1a938',
    messagingSenderId: '570073970473',
    projectId: 'facial-flutter',
    authDomain: 'facial-flutter.firebaseapp.com',
    storageBucket: 'facial-flutter.firebasestorage.app',
    measurementId: 'G-QYEJCJ9JTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZm5TpVs6iB64lu3QOipofRHZdzrEFEUE',
    appId: '1:570073970473:android:f90e286eeec56051a1a938',
    messagingSenderId: '570073970473',
    projectId: 'facial-flutter',
    storageBucket: 'facial-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPVSZJsF3sv8B-fAFvujZHIVV_SpLRA_g',
    appId: '1:570073970473:ios:1ec86a132c9ab121a1a938',
    messagingSenderId: '570073970473',
    projectId: 'facial-flutter',
    storageBucket: 'facial-flutter.firebasestorage.app',
    iosBundleId: 'com.example.facial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPVSZJsF3sv8B-fAFvujZHIVV_SpLRA_g',
    appId: '1:570073970473:ios:1ec86a132c9ab121a1a938',
    messagingSenderId: '570073970473',
    projectId: 'facial-flutter',
    storageBucket: 'facial-flutter.firebasestorage.app',
    iosBundleId: 'com.example.facial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9MuqAGoPnpsLiDZ86g9Z4rGhbFcQHAUw',
    appId: '1:570073970473:web:324d918f7c1c2b51a1a938',
    messagingSenderId: '570073970473',
    projectId: 'facial-flutter',
    authDomain: 'facial-flutter.firebaseapp.com',
    storageBucket: 'facial-flutter.firebasestorage.app',
    measurementId: 'G-EJ6CBMTZL5',
  );
}
